<%
def boxen?; ENV['BOXEN_HOME']; end

socket = [
  ENV["BOXEN_MYSQL_SOCKET"],
    "/var/run/mysql5/mysqld.sock",
    "/tmp/mysql.sock"
].compact.detect { |f| File.exist? f  }

port = ENV["BOXEN_MYSQL_PORT"] || "3306"
%>

development:
  adapter: mysql2
  database: marketplace_development
  username: root
  password:
  <% if socket %>
  host: localhost
  socket: <%= socket %>
  <% else %>
  host: 127.0.0.1
  port: <%= port %>
  <% end %>
  reconnect: true
  encoding: utf8
  collation: utf8_general_ci
